stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - config.yaml
    outs:
      - data/raw/final_satellite_indices.csv
      - data/raw/annotations.csv